#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    // VIPS仕様: 他チェーン（HTMLCOIN）のポート4888混信IP配列を一掃し、動的DNSシード接続へ最適化
};

static const uint8_t chainparams_seed_test[] = {
    // VIPS仕様: クリーンアップ
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
